default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: elevennote_development

test:
  <<: *default
  database: elevennote_test

production:
  <<: *default
  database: elevennote_production
  username: elevennote
  password: <%= ENV['ELEVENNOTE_DATABASE_PASSWORD'] %>
